title: Isaac Miti | ikayz
description: My person website which contains information about me and the projects I have worked on.
twitter_username: @ikayz360
github_username: ikayz
theme: jekyll-theme-cayman
